<a href="https://colab.research.google.com/github/zidniryi/ML_python/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np

Scalar Tensor

In [12]:
rank_0_tensor = tf.constant(11)

In [13]:
print(rank_0_tensor)

tf.Tensor(11, shape=(), dtype=int32)


Vector = Array

In [14]:
rank_1_tensor = tf.constant([11,22,44,11])

In [16]:
print(rank_1_tensor)

tf.Tensor([11 22 44 11], shape=(4,), dtype=int32)


Matrix

In [23]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [24]:
rank_2s_tensor = tf.constant([[2, 2],
                             [8, 4],
                             [5, 6]], dtype=tf.float16)


In [25]:
rank_matrix_sum = rank_2_tensor + rank_2s_tensor
print(rank_matrix_sum)

tf.Tensor(
[[ 3.  4.]
 [11.  8.]
 [10. 12.]], shape=(3, 2), dtype=float16)


3 Tensor

In [26]:
rank_3_tensor = tf.constant([[[11,111,1000], [22,222,2000]],
                            [[33,333,3000], [44,444,4000]],
                            [[55,555,5000], [66,666,6000]]
                             ])

In [27]:
print(rank_3_tensor)

tf.Tensor(
[[[  11  111 1000]
  [  22  222 2000]]

 [[  33  333 3000]
  [  44  444 4000]]

 [[  55  555 5000]
  [  66  666 6000]]], shape=(3, 2, 3), dtype=int32)


Konversi ke Numpy

In [28]:
np.array(rank_0_tensor)

array(11, dtype=int32)

In [29]:
np.array(rank_1_tensor)

array([11, 22, 44, 11], dtype=int32)

In [30]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [31]:
np.array(rank_3_tensor)

array([[[  11,  111, 1000],
        [  22,  222, 2000]],

       [[  33,  333, 3000],
        [  44,  444, 4000]],

       [[  55,  555, 5000],
        [  66,  666, 6000]]], dtype=int32)

Tensor Flow Operation

In [32]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



You can use math operation

In [35]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication
print(a / b, "\n") # matrix multiplication


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64) 



Operation like max etc

In [37]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))
# Numpy Convert soo nice
print(tf.cos(c).numpy())


tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)
[[-0.6536436  0.2836622]
 [-0.8390715  0.5403023]]
