<a href="https://colab.research.google.com/github/zidniryi/ML_python/blob/main/TensorFlow_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np

Scalar Tensor

In [12]:
rank_0_tensor = tf.constant(11)

In [13]:
print(rank_0_tensor)

tf.Tensor(11, shape=(), dtype=int32)


Vector = Array

In [14]:
rank_1_tensor = tf.constant([11,22,44,11])

In [16]:
print(rank_1_tensor)

tf.Tensor([11 22 44 11], shape=(4,), dtype=int32)


Matrix

In [23]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [24]:
rank_2s_tensor = tf.constant([[2, 2],
                             [8, 4],
                             [5, 6]], dtype=tf.float16)


In [25]:
rank_matrix_sum = rank_2_tensor + rank_2s_tensor
print(rank_matrix_sum)

tf.Tensor(
[[ 3.  4.]
 [11.  8.]
 [10. 12.]], shape=(3, 2), dtype=float16)
